require:
  - rubocop-rails
  - rubocop-performance

# Common configuration.
AllCops:
  # Disable cop pending
  NewCops: disable
  # Ignore message suggest extensions
  SuggestExtensions:
    rubocop-rspec: false
  # Include gemspec and Rakefile
  Include:
    - '**/*.rb'
    - '**/*.gemspec'
    - '**/Rakefile'
    - '**/config.ru'
    - 'config/initializers/*'
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - 'db/*'
    - 'spec/*'
    - 'config/*'
    - 'config/environments/*'
    - 'config/routes/*'
    - 'node_modules/**/*'
