require:
  - rubocop-rails
  - rubocop-performance

# Common configuration.
AllCops:
  NewCops: disable
  SuggestExtensions:
    rubocop-rspec: false
  Include:
    - '**/*.rb'
    - '**/*.gemspec'
    - '**/Rakefile'
    - '**/config.ru'
    - 'config/initializers/*'
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - 'db/*'
    - 'spec/*'
    - 'config/*'
    - 'config/environments/*'
    - 'config/routes/*'
    - 'node_modules/**/*'

# Temporary configuration
Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false
