version: 0.2

phases:
  install:
    commands:
      - >-
        aws ecr get-login-password --region $AWS_DEFAULT_REGION |
        docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker pull $REPO_URL:$REF_NAME || true

  pre_build:
    commands:
      - docker build --file Dockerfile --cache-from $REPO_URL:$REF_NAME --tag $REPO_URL:test .

  build:
    commands:
      - docker-compose --file docker-compose.ci.yml run rspec

  post_build:
    commands:
      - docker push $REPO_URL