version: "3"
services:
  db:
    image: mysql:5.7
    restart: on-failure
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql

  rspec:
    image: 374357701248.dkr.ecr.ap-northeast-1.amazonaws.com/allan/rails:latest
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: /scripts/run-tests.sh