name: Run Codebuild
on: [push, pull_request]
permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql_test:
        image: mysql:5.7
        environment:
          MYSQL_DATABASE: myapp_test
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.5
      - name: Bundle Install
        run: |
          gem install bundler
          bundle install
      - name: Prepare and Test
        run: |
          bundle exec rake db:schema:load db:migrate
          bundle exec rspec