name: Run Codebuild
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: myapp_test
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.5
      - name: Bundle Install
        run: |
          gem install bundler
          bundle install
      - name: Prepare and Test
        run: |
          bundle exec rake db:schema:load db:migrate
          bundle exec rspec